### ISSUE TITLE
Background image not filling the area in modal

### ISSUE THREAD

**Issue by junaid1840** [advanced-cropper/react-advanced-cropper#20]
Hi I'm having some trouble setting the image to crop. 
There is some padding or gap on right and bottom to the crop-able box.
I'm using Next.js

![Screenshot 2023-01-11 at 2 42 17 AM](https://user-images.githubusercontent.com/51792110/211668829-05d52b38-15f9-4601-addc-a64abcefd020.png)
This is how I integrated the the library.
```
import { CropperRef, Cropper, RectangleStencil } from 'react-advanced-cropper'
import 'react-advanced-cropper/dist/style.css'
import 'react-advanced-cropper/dist/themes/corners.css'

export const InputImageCropper = ({
  id,
  openModal,
  onSave,
  onClose,
  src
  stencilComponent = RectangleStencil,
  ...props
}: Prop) => {
  const cropperRef = useRef<CropperRef>(null)

  return (
    <>
      <Modal
        header="Select image"
        open={openModal}
        onClose={onClose}
        size="xl"
        footer={
          <>
            <Button onClick={onClose} variant="text" color="secondary">
              Cancel
            </Button>
            <Button onClick={onSave}>Save</Button>
          </>
        }
      >
        <Cropper
          ref={cropperRef}
          src={src}
          stencilComponent={stencilComponent}
          {...props}
        />
      </Modal>
    </>
  )
}

```

**Comment by Norserium** [comment]
@junaid1840, that's important bug.

Try to place the cropper outside the modal window and reproduce bug. If it's reproducing, send me the used image.

**Comment by junaid1840** [comment]
@Norserium You are absolutely correct. Thanks

1. Resizing the window does fix the issue.
2. Yes it is working fine outside the modal.

Any solution for dynamic width setting or maybe  lazy loading the cropper ?

**Comment by Norserium** [comment]
@junaid1840, what's library do you use for the modal window? Why does it change the size when it's openning?

**Comment by junaid1840** [comment]
@Norserium I'm using Chakra UI and tailwind for styling.
https://chakra-ui.com/
https://tailwindcss.com/

**Comment by Norserium** [comment]
@junaid1840, well, the problem is that the cropper doesn't work correctly when you apply to the parent container the scale transformation. 

That's because the cropper uses `getBoundingClientRect` under the hood to get the boundary size instead of `clientWidth` and `clientHeight. That was needed to get the better subpixel precision required by the preview component.

But there is the hope.

Unfortunately, Chakra UI doesn't provide `onOpened` prop, that will be called, when the transition is completed.  That would give you the possibility to display the cropper when the modals is finally opened or the possibility to call `refresh()` method to update the cropper like it's updating on window resize.

What can I offer you in this situtation?

1. Change the transition animation from `"scale"` to something else.
2. Try to process `onTransitionEnd` callback by himself and detect when the modal is finally opened, but be careful, there will be a lot of that events. It should solve your issue.
3. This cropper is incredible flex and you can redefine the boundary size calculation that causes this issue initially. [The example for the latest (it's important) version](https://codesandbox.io/s/react-advanced-cropper-modal-redefine-size-gh8p6i?file=/src/index.tsx).

**Comment by Norserium** [comment]
@junaid1840, I close issue. Feel free to reopen it if the advice above didn't help you.

**Comment by ronyfhebrian** [comment]
The responsiveness of your answer and also providing solution are amazing.
I also have this issue using HeadlessUI (official tailwind component for React) and having this issue as well.
Your solution is working on this modal. Thank you!

**Comment by Norserium** [comment]
@ronyfhebrian, I'm happy to hear that. Good luck!
