### ISSUE TITLE
Image position limitations

### ISSUE THREAD

**Issue by RiaanWest** [advanced-cropper/react-advanced-cropper#26]
Thank you for a great library - super happy with it so far!

I would like to get some advise on how to prevent this type of situation when doing image rotation (i.e. the image is not covering the crop area):
![image](https://user-images.githubusercontent.com/67014/225281498-9862bedc-c8dc-44d9-9861-56752942d96e.png)

[In the `mobile-cropper` example](https://advanced-cropper.github.io/react-advanced-cropper/#mobile-cropper), there seems to be some post-transform position adjustments that is implemented. Is there a way to have this type of functionality, using `react-advanced-cropper`? I'd prefer to not make use of `react-mobile-cropper`, because it seems to get fewer updates.

**Comment by Norserium** [comment]
@RiaanWest, I'm the author both `react-advanced-cropper` and `react-mobile-cropper`, so it's pretty safe use any of them. 

It's safer than implement this behavior by yourself, but you of course can look into the sources of the last one and copy-paste [the code](https://github.com/advanced-cropper/react-mobile-cropper/blob/master/src/components/Cropper.tsx). It's pretty simple, because it uses the algorithms from `advanced-cropper` library.

**Comment by RiaanWest** [comment]
Thanks for the quick reply, appreciate it. I'm going to give the algorithms a go, and see if I can get it working. So far, it's looking good: https://react-ts-yzruzg.stackblitz.io

**Comment by Norserium** [comment]
@RiaanWest, is your issue still actual?

**Comment by RiaanWest** [comment]
I'm happy for you to close this - I managed to use the algorithms from `advanced-cropper` to produce what we needed. Thanks again.
