### ISSUE TITLE
Prevent zooming at all

### ISSUE THREAD

**Issue by pchr-srf** [advanced-cropper/react-advanced-cropper#6]
How can I prevent zooming of the image via Scrollwheel/touchpad completely?

**Comment by Norserium** [comment]
@pchr-srf, nice to meet you again!

The image can be zoomed due two reasons by default:
1. By processing the scroll wheel event and touch events inside `backgroundWrapper` (i.e. `CropperBackgroundWrapper` by default). You can disable it by pass to this component corresponding prop:
```
<Cropper
    backgroundWrapperProps={{
        scaleImage: false
    }}
/>
```
2. The image can be scaled due to resize of the cropper, due to the state reconciling and etc. Perhaps, you have the cropper with static width and height and it's not your case, but I should warn you about that. The most simple way to deal with this kind of image scaling is using of custom postprocess:
```
import { preventZoom } from "advanced-cropper/extensions/prevent-zoom";
```
```
<Cropper
    postProcess={preventZoom}
    backgroundWrapperProps={{
        scaleImage: false
    }}
/>
```

There is [the example](https://codesandbox.io/s/react-advanced-cropper-disable-zoom-eh2670?file=/src/index.tsx:385-410).

**Comment by pchr-srf** [comment]
Hello hello!

Perfect, 
```js
backgroundWrapperProps={{
    scaleImage: false
}}
```

worked like a charm 👏

Thank you very much, did not notice that one in the docs!
