### ISSUE TITLE
How to remove auto zooming when aspectration is change?

### ISSUE THREAD

**Issue by mjapadilla** [advanced-cropper/react-advanced-cropper#7]

**Comment by Norserium** [comment]
@mjapadilla, could you provide the codesandbox for your use-case? Or you can send the video that illustrates your issue.

**Comment by mjapadilla** [comment]
![image](https://user-images.githubusercontent.com/56869280/190184645-ec309204-4105-4ff2-912a-e194655ab791.png)

I dont know if this is safe. i just call reset function

**Comment by Norserium** [comment]
@mjapadilla, it should be pretty safe. But what do you want to get? What's problem do you solve?

**Comment by mjapadilla** [comment]
https://user-images.githubusercontent.com/56869280/190291542-86bc8cc2-86e8-4744-91af-8fbca2e773af.mov

My goal is to prevent auto zooming of image when aspect ratio is change

**Comment by mjapadilla** [comment]
In documentation it says i need to set autoZoom to false like this?

![image](https://user-images.githubusercontent.com/56869280/190291787-a7171b5c-91b7-4cf2-abd0-eddee711f214.png)

**Comment by Norserium** [comment]
@mjapadilla, well, `autoZoom` is the deprecated property. It should be disabled by default. What's going on if you remove that prop at all? What's version of `react-advanced-cropper` do you use?

**Comment by mjapadilla** [comment]
Im using 0.11.0 version

**Comment by Norserium** [comment]
@mjapadilla, could you record a video? I think I know what you are talking about, but I need to check.

**Comment by mjapadilla** [comment]
https://user-images.githubusercontent.com/56869280/190542135-2abea433-84aa-45eb-9a9e-de9955828770.mov

@Norserium here mate

**Comment by Norserium** [comment]
@mjapadilla, I see, thank you. 

It's the result of the state reconciling, i.e. transforming the state to correspond new cropper settings. I still trying to decide what's the best way to deal with its different aspects.

When you change the aspect ratio the cropper doesn't reset state, instead it tries to adapt the state to the changes. Looking at other croppers, I see that some of them resets the cropper on the aspect-ratio change, some of them does the same thing that do I.

What can I do in this situation.

The current state:

https://user-images.githubusercontent.com/9862719/190640469-2b4efde9-90dd-4069-9cc6-3a0f1e6ce568.mp4

The alternative:

https://user-images.githubusercontent.com/9862719/190640692-99f8c75f-7e58-4b2d-8a23-dca392c39432.mp4

Perhaps, the alternative is better.

Of course, also you can reset the state after change the aspect ratio, but I suppose it should not be a default behavior. You can reset the cropper by the corresponding method. Why? Because you lost all your state (it's illustrated at the end of the video).

https://user-images.githubusercontent.com/9862719/190643079-f29c59f2-36a5-46f1-a2c1-0c089bfbd6a2.mp4

**Comment by Norserium** [comment]
@mjapadilla, I suppose I will implement the behavior that you can see on the second video in the previous message. It looks more predictable.

**Comment by Norserium** [comment]
@mjapadilla, it's available in `0.11.1`. Also I fix the little flickering that I seen on the cropper reset after the aspect-ratio change.

**Comment by Norserium** [comment]
@mjapadilla, also I add the experimental prop `autoReconcile`, that is enabled by default. It allows to disable the auto reconciling and do it on your own side or not to do.

_If you use it, add the some emote to this message. Probably, I will do something with them in the near future, and I will inform you about it._

**Comment by Norserium** [comment]
@mjapadilla, any news?

**Comment by mjapadilla** [comment]
@Norserium i updated the version im using and now im getting error.
![image](https://user-images.githubusercontent.com/56869280/191886310-eda9a63d-c898-4f63-a2a0-d7f857cd3515.png)

**Comment by mjapadilla** [comment]
@Norserium  its all goods now, i will close this issue now, thanks mate

**Comment by Norserium** [comment]
@mjapadilla, you are welcome!
